### ISSUE TITLE
RW count in Generated Report

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/cognicity-analytics#19]
Hi @talltom. The list of RW is really helpful! (rather than only number of RWs as we planned initially)
However it seems like the range of flood depths in generated report is the highest range. For example:

![image](https://user-images.githubusercontent.com/22338984/35904546-0ef55ebe-0c16-11e8-9610-8416a17ca537.png)
![image](https://user-images.githubusercontent.com/22338984/35904554-158d88d2-0c16-11e8-8f8e-52bfa945d938.png)

It shows that RW 05 in Bidara Cina is also in moderate state while the public map shows that it is on minor state:
![image](https://user-images.githubusercontent.com/22338984/35904538-048936d0-0c16-11e8-88d2-518b45fb1d51.png)

Perhaps it can be corrected so it would be more or less like this sketch:
![scangithub](https://user-images.githubusercontent.com/22338984/35905200-cb8e303a-0c18-11e8-9f46-52369bcd05b0.jpg)

**Comment by ojha-url** [comment]
Clarifying for self:
Group RW's as per their actual highest flood state in the given period
(instead of computing the max flood state of all RW's in a parent area)
