### ISSUE TITLE
Firefox language selector UI bug

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-analytics#26]
(even after manually navigating to dashboard as shown, also visible in screenshot in https://github.com/urbanriskmap/cognicity-analytics/issues/25)
<img width="156" alt="screenshot 2018-02-08 12 25 26" src="https://user-images.githubusercontent.com/2288238/35950568-450e9e7e-0ccb-11e8-839a-10113e050d96.png">

**Comment by ojha-url** [comment]
For self:
https://stackoverflow.com/questions/26306864/firefox-float-bug-how-do-i-get-my-floatright-on-the-same-line
