### ISSUE TITLE
Fix date formats to DD/MM/YY

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/cognicity-analytics#5]
https://material.angular.io/components/datepicker/overview#internationalization

**Comment by tomasholderness** [comment]
also:
- need time zone environment parameter per deployment
- fix times (slider and graph) in dashboard to be local time

**Comment by ojha-url** [comment]
Fixed via 4e90be659f3c0192569a9d82a4f4f3862905ad6e
